### ISSUE TITLE
Unable to edit request

### ISSUE THREAD

**Issue by charlesosj** [OfficeDev/microsoft-teams-apps-buildingaccess#10]
Hi, I've come upon an issue where, in the request summary galleries if you remove a request, it just recollects all the items in the save and next buttons to the colNewDatesNotOccupied collection each time, so you cant actually edit the days and creates all of them even if you have removed days, I've uploaded a video which shows this 
Thanks in advance!

https://youtu.be/VB76G98uuLQ

**Comment by abbodh** [comment]
This should be resolved by #12

**Comment by yashrajmungale** [comment]
Closing this as it is fixed and verified. @charlesosj Please let us know if you have the same issue after using the updated packages from the main branch.
