### ISSUE TITLE
QR Code Not Found

### ISSUE THREAD

**Issue by CaptStealth** [OfficeDev/microsoft-teams-apps-buildingaccess#11]
I get an error when I use the Building Security App on my phone to scan the QR code in the pass. it says "Not found". That is the QR code cannot be found
![IMG_9FC021A2EC6C-1](https://user-images.githubusercontent.com/72608427/95735991-e9f0fb00-0c85-11eb-8391-2032e305d03a.jpeg)

**Comment by yashrajmungale** [comment]
Can you please list down the repro steps?

**Comment by CaptStealth** [comment]
Thanks. I've been able to identify the cause of the issue and fixed it. You have to select the building before validating the access key
