### ISSUE TITLE
Issue with PowerBi Dashboard

### ISSUE THREAD

**Issue by sethmtut** [OfficeDev/microsoft-teams-apps-buildingaccess#14]
Hi Guys, 

I am having trouble getting the PowerBi dashboard to connect to the sharepoint lists / tables

I have followed the instructions to the letter and entered the Sharepoint lists GUID ID, account has full permission to the site, however it just will not have it.

Expression error: The key didnt match any rows in the table

Clicking "Go to Error" and edit settings opens up the resource navigator and i can select the table that way, however it just loads it briefly then errors again. Any ideas?

![PowerBiBildingapp](https://user-images.githubusercontent.com/72934225/96152341-5a0cb480-0f04-11eb-9516-dc3d20181bca.JPG)

many thanks

**Comment by yashrajmungale** [comment]
By looking at the error, I presume it might that the GUIDs to the SP list is wrong or some of the columns which might be referenced in the Power BI do not exist. 

- Check the GUIDs of all the SP lists if they are correct
- Check if you have all the columns as mentioned in the deployment-guide/data-sources

**Comment by yashrajmungale** [comment]
Closing this as we have not received an update. Please reopen , if the issue persists
