### ISSUE TITLE
Issue when trying to import BARCalendarReservation

### ISSUE THREAD

**Issue by JMoyersons** [OfficeDev/microsoft-teams-apps-buildingaccess#15]
When importing BARCalendarReservation, I add the SP and O365 Outlook connections, but a while after I hit import it gives me an error.

Flow save failed with code 'DynamicOperationRequestClientFailure' and message 'The dynamic operation request to API 'sharepointonline' operation 'GetTable' failed with status code 'Unauthorized'. This may indicate invalid input parameters. Error response: { "error_description": "Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown." }'.

**Comment by JMoyersons** [comment]
resolved, DLP issue

**Comment by makandmozart** [comment]
TODAY November 16, 2020, download the full application

I import the BARCalendarReservation but it marks the same error reported in this issue

Do I need to do something special?
Do I need to download something special?

**Comment by annigam01** [comment]
while importing the solution BARCalendarReservation, this comes up, i have 0 DLP in PowerPlatform

**Comment by 0Emma0** [comment]
Hello, I have the same error. Have you been able to fix it?
