### ISSUE TITLE
Notify Requestor Always Notifies as Approved even when Rejected

### ISSUE THREAD

**Issue by mshflip72** [OfficeDev/microsoft-teams-apps-buildingaccess#16]
In BARNotifyRequestor the final step, Post a message to the user as a Flow bot, declares a Heading of "Onsite Request Approved". 

This means that even if a request is rejected the Headline of the Flow Post as the requestor receives makes it appear as if it was approved.

To resolve this Initialize a new variable (e.g. varPostHeading) of type String prior to the switch statement. In the switch approved and rejected steps, set it to the relevant string (eg. in Approved - "Onsite Request Approved", in Rejected - "Onsite Request Rejected"). Finally, in the Post a message to the user as a Flow bot step, use the variable as the Heading.

**Comment by yashrajmungale** [comment]
Hi @mshflip72 are you talking about the personal flow notification the user receives when the request is approved/rejected? Can you please send us a screenshot if you have it handy? When we checked, we were getting notifications with appropriate heading. Just want to make sure we understood your issue

**Comment by mshflip72** [comment]
Hi - yes I am talking about the personal flow notification to the requestor stating whether request is approved or rejected. 

As you can see from below screenshot, the two notifications both have a heading of Approved but actually have been rejected (they have a rejection reason in them) 
![Screenshot_20201028_160136](https://user-images.githubusercontent.com/73282188/97462742-f4262100-1936-11eb-815a-12e004635da2.jpg)
