### ISSUE TITLE
Approver unidentified

### ISSUE THREAD

**Issue by mshflip72** [OfficeDev/microsoft-teams-apps-buildingaccess#17]
Uploaded data to AD manager attribute a day ago.
This version of the App not recognising this and still sending approvals to Teams site instead of Approvers chat. 

Checked earlier version of app against same AD and approver is identified and approvals are sent to them.

If you can tell me where in app approver is identified can cross reference against earlier version to see if I can identify difference.

**Comment by yashrajmungale** [comment]
@mshflip72 Thanks for writing to us. We will validate this and get back to you.

**Comment by mshflip72** [comment]
Have been able to resolve this by removing the code determining whether selected building has a default approver from the lblapprovername_3 element of the power app. Not sure why this resolved it.
