### ISSUE TITLE
I keep receiving the error with the PowerBI

### ISSUE THREAD

**Issue by dalejose** [OfficeDev/microsoft-teams-apps-buildingaccess#20]
Please see error

![image](https://user-images.githubusercontent.com/44021396/98528014-ae624480-22b6-11eb-902f-0b634883b70a.png)

**Comment by yashrajmungale** [comment]
@dalejose Can you verify the SharePoint list ID is correct or that the list is not deleted? Usually we get such issues when a list is recreated. In such scenarios the List ID changes too.

**Comment by v-smahaj** [comment]
Before importing the package, navigate to BARCalendarReservation.zip\Microsoft.Flow\flows\385cb5b1-c6c5-460a-bc7a-34b378bf7568\definition file and replace your SharePoint Site URL in place of existing one. Then, Save and import.
Let us know if issue still persists.
