### ISSUE TITLE
Reopen issue Issue when trying to import BARCalendarReservation #15

### ISSUE THREAD

**Issue by makandmozart** [OfficeDev/microsoft-teams-apps-buildingaccess#23]
I open this issue again

today November 18, 2020, downloading the complete package I keep registering this same error

Do I need to do something special?
Do I need to download something special?

![flow1](https://user-images.githubusercontent.com/72475901/99542204-63f85c00-2977-11eb-826c-e6489f425792.PNG)
![flow2](https://user-images.githubusercontent.com/72475901/99542206-6490f280-2977-11eb-8c40-1304ad7bad47.PNG)
![flow3](https://user-images.githubusercontent.com/72475901/99542202-635fc580-2977-11eb-88d9-fe3b308ac978.PNG)

**Comment by LowManOnTotem** [comment]
I am also having the same issue when importing with the same error.

**Comment by makandmozart** [comment]
Today, December 6, 2020, the error continues, even with the new file published on November 24, 20202, I do not see that it is correct to force the installation


![Capture](https://user-images.githubusercontent.com/72475901/101298229-92d55580-37f2-11eb-9dcb-e155a3b9a3cf.PNG)

**Comment by joaquinhuante** [comment]
There is a third level condition that it has to be updated with the correct connection value, after that, you can save it
![imagen](https://user-images.githubusercontent.com/6798634/112078757-97750e00-8b44-11eb-8b38-bf797a2e7136.png)

**Comment by v-smahaj** [comment]
Before importing the package, Navigate to BARCalendarReservation.zip\Microsoft.Flow\flows\385cb5b1-c6c5-460a-bc7a-34b378bf7568\definition file and replace your SharePoint Site URL in place of existing one. Then, Save and import.
