### ISSUE TITLE
Building Access App

### ISSUE THREAD

**Issue by rhysieboy** [OfficeDev/microsoft-teams-apps-buildingaccess#28]
Hi

The building access app appears to break when I add the BAR_appSettings & BAR_requests sharepoint datastores.  I lose the 2 home screen buttons so there is no data when playing the app and get the function filter has some invalid arguments. Doesnt seem to like **isslotbooked** I'm new to Powerapps so any help would be much appreciated. I've attached a couple of screenshots showing the issue
![error code](https://user-images.githubusercontent.com/76165028/102490656-03883780-4067-11eb-8d45-bd3731670cc3.PNG)

![error homescreen](https://user-images.githubusercontent.com/76165028/102491778-9d9caf80-4068-11eb-881e-d56819684c5b.png)

**Comment by graveyard86** [comment]
i have same issue with same error.
can anybody help?

**Comment by marton-szabo-bbi** [comment]
Hello, i have the same issue apparently. It seems that the 2 fields IsSlotBooked and IsRequired are not created somewhere -- perhaps in one of the lists? I tried to look for it among the definitions in the package files, but only found one flow reference in the BuildingAccess.zip file. Can you help to resolve this please?

**Comment by mpntuli** [comment]
Hi,
On your BAR_Requests list add IsSlotBooked and IsRequired Columns. then refresh your data source list. it should be fine after that.

![image](https://user-images.githubusercontent.com/72565400/106604681-a38f1700-6568-11eb-915c-9920a8d4776a.png)

**Comment by marton-szabo-bbi** [comment]
Hi, indeed, I figured it in the meantime and it indeed works now. Thanks a lot  for your answer anyway! Also, just to add that those 2 columns should be of type "Choice Yes/No" in terms of Sharepoint.

**Comment by mpntuli** [comment]
Hi All,

Anyone experiencing below issues with the app:
1. BARNotify approver working not triggering when new item is added in the BAR_Request list?
2. When submitting a new item it submits more than one request items to the list?
3. My request screen is not showing any of the summitted requests?

Kindly share your thoughts.
Thanks

**Comment by rhysieboy** [comment]
Hi

Thanks for the fix regarding the BAR_Requests list, but i'm now having the same issues as described above.

Thanks

**Comment by hsantan** [comment]
I faced the same issue and was fixed adding this two additional fields.

**Comment by marton-szabo-bbi** [comment]
> Hi All,
> 
> Anyone experiencing below issues with the app:
> 
> 1. BARNotifyApprover flow not triggering when new item is added in the BAR_Request list?
> 2. When submitting a new item it submits more than one request items to the list?
> 3. My request screen is not showing any of the summitted requests?
> 
> Kindly share your thoughts.
> Thanks

Hi, I haven't experienced these issues. I guess you already checked if the flow is enabled?
For the requests not being displayed: can you see them in the BAR_Requests SP list?

**Comment by mpntuli** [comment]
> > Hi All,
> > Anyone experiencing below issues with the app:
> > 
> > 1. BARNotifyApprover flow not triggering when new item is added in the BAR_Request list?
> > 2. When submitting a new item it submits more than one request items to the list?
> > 3. My request screen is not showing any of the summitted requests?
> > 
> > Kindly share your thoughts.
> > Thanks
> 
> Hi, I haven't experienced these issues. I guess you already checked if the flow is enabled?
> For the requests not being displayed: can you see them in the BAR_Requests SP list?

YEs i checked and its enabled, and yes i can see the items on the list

**Comment by mpntuli** [comment]
> Hi All,
> 
> Anyone experiencing below issues with the app:
> 
> 1. BARNotifyApprover flow not triggering when new item is added in the BAR_Request list?
> 2. When submitting a new item it submits more than one request items to the list?
> 3. My request screen is not showing any of the summitted requests?
> 
> Kindly share your thoughts.
> Thanks

Hi All,

All issues resolved now.

Thanks

**Comment by rhysieboy** [comment]
> 
> 
> > Hi All,
> > Anyone experiencing below issues with the app:
> > 
> > 1. BARNotifyApprover flow not triggering when new item is added in the BAR_Request list?
> > 2. When submitting a new item it submits more than one request items to the list?
> > 3. My request screen is not showing any of the summitted requests?
> > 
> > Kindly share your thoughts.
> > Thanks
> 
> Hi All,
> 
> All issues resolved now.
> 
> Thanks

How did you resolve the issues?

**Comment by mpntuli** [comment]
> > > Hi All,
> > > Anyone experiencing below issues with the app:
> > > 
> > > 1. BARNotifyApprover flow not triggering when new item is added in the BAR_Request list?
> > > 2. When submitting a new item it submits more than one request items to the list?
> > > 3. My request screen is not showing any of the summitted requests?
> > > 
> > > Kindly share your thoughts.
> > > Thanks
> > 
> > 
> > Hi All,
> > All issues resolved now.
> > Thanks
> 
> How did you resolve the issues?

I had to redo everything from scratch, Seems like i missed some steps on the guide

**Comment by v-smahaj** [comment]
Thanks for reporting. We have pushed updated code in this repo.
Can you try new deployment from scratch with latest code.
Let us know if issue still persists.

**Comment by Lan-BZ** [comment]
when an user submitted a new request , the Building Access App sent three copies of such a request to the BAR_Requests list in SharePoint. It's triple requests for every request. Anyone knows how to fix such a problem; please advise me. Many thanks. Lana
