### ISSUE TITLE
Feature Request - Allow Admin Setting for Number of concurrent booking per day.

### ISSUE THREAD

**Issue by bungleweed** [OfficeDev/microsoft-teams-apps-buildingaccess#31]
Hi,

There is a scenario even with the times slots option where someone might want to book different buildings on the same day. For example you could be working out of Building A in the morning, and then Building B in the afternoon. At the moment you cannot make multiple reservations on the same day. Could this be added as a parameter you can conifgure in the Admin Settings? So for example Number of concurrent bookings per day and the ability to set this greater than 1.

**Comment by v-smahaj** [comment]
For Building Access repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
