### ISSUE TITLE
Bookings are registering 2 per request when i have 1 time slot

### ISSUE THREAD

**Issue by scottylan0140** [OfficeDev/microsoft-teams-apps-buildingaccess#32]
When we submit a request, we are selecting Full Day for the request.  
In the setup, i did have an option for 9am-5pm as well, but we have told users to select Full Day

When we submit for the full day, we get an entry in the request table for each time slot, and there for the total requests/number of people on sites are duplicating. 
Ie;  a request for Full Day, and a request for 9am-5pm..

 ive attached a extract of the BAR_Requests table

How can we fix this?  I did try removing the time slots, but it seemed to stop working if i didnt have one in there.

Would love some help on this one.

Thanks in advance guys, great app.

[BAR_REquests.xlsx](https://github.com/OfficeDev/microsoft-teams-apps-buildingaccess/files/5955913/BAR_REquests.xlsx)

**Comment by yashrajmungale** [comment]
@scottylan0140 We have modified the package in the main branch to resolve some bugs. Can you please take the latest version and see if you are still able to repro the issue?

**Comment by scottylan0140** [comment]
Hi team,  yes it seems that the issue is still there.   Booking a locaiton for a full day, if i have timeslots specified but not sleected, a request is created for each time slot, although only 1 is marked as IsRequired = yes

**Comment by GHNinja** [comment]
@yashrajmungale - we seem to have the same issue - App required atleast 2 time slots, it then creates 3 entries in the SharePoint list one  @for full day and 2 for other time slots. 

@scottylan0140 - we are having similar issue when a users withdraws a request and then unable to view any further space availability. if a user chooses to book only a time slot and not full day, it doesn't show up in the 'my requests' section for the user. do you have the same issue upon request withdrawal ?

**Comment by bhabhat** [comment]
Hi Team - Facing the same issue. If there are N timeslots, for every request N+1 entries are created in the list - 1 for each timeslot & 1 for Full day (with the actual blocked timeslot having isRequired=yes)

**Comment by GHNinja** [comment]
> Hi Team - Facing the same issue. If there are N timeslots, for every request N+1 entries are created in the list - 1 for each timeslot & 1 for Full day (with the actual blocked timeslot having isRequired=yes)

This is the intended behaviour of the App to create 1 full day booking entry and further entries for each time slot, 
how is this causing an issue ?

**Comment by bhabhat** [comment]
> > Hi Team - Facing the same issue. If there are N timeslots, for every request N+1 entries are created in the list - 1 for each timeslot & 1 for Full day (with the actual blocked timeslot having isRequired=yes)
> 
> This is the intended behaviour of the App to create 1 full day booking entry and further entries for each time slot,
> how is this causing an issue ?

Thanks for clarifying that this is not an issue. From the earlier comments on this ticket, I assumed it was one. 
I hope there would not be any performance issues with somany entries on that list. Appreciate if you could please clarify. Thanks.
