### ISSUE TITLE
Authorization error on DeploySPLists

### ISSUE THREAD

**Issue by camigliore** [OfficeDev/microsoft-teams-apps-buildingaccess#37]
Attempting to deploy this app with no previous experience... I'm a complete newbie at this.  Encountered an authorization error on the Scope - Logo Library step of the DeploySPLists flow.  Any assistance would be appreciated.  Here is a screenshot:
![image](https://user-images.githubusercontent.com/80854727/111532396-fea55380-873b-11eb-9ba9-57e6bdfbe0c1.png)

**Comment by v-smahaj** [comment]
We are not able to repro this issue at our end.
Let us know if issue still persists.
