### ISSUE TITLE
DeploySPLists always fails when performing "Add ... to Default View"

### ISSUE THREAD

**Issue by ikukoyoneda** [OfficeDev/microsoft-teams-apps-buildingaccess#4]
DeploySPLists fails in each step of "Add ... to Default View" with HTTP 400 and cannot create SharePoint lists. Removing all "Add ... to Default view" steps resolve the issue.

**Comment by yashrajmungale** [comment]
Thank you for writing to us. Let us re verify the steps and get back to you

**Comment by gbulacio** [comment]
Gracias!
