### ISSUE TITLE
List View Threshold hit in Building Access app

### ISSUE THREAD

**Issue by modery** [OfficeDev/microsoft-teams-apps-buildingaccess#40]
We did it! We crossed 5,000 requests and are thus now encountering the List View Threshold error in the Building Access app, "My Requests" screen:
`The requested operation is invalid. Server Response: BAR_Requests failed: The attempted operation is prohibited because it exceeds the list view threshold. `

We are using the app for one location only, thus we only have one building in use. As it has been in use for more than 3.5 months now, a lot of data came in.

**Solution**
Managed to fix it by creating an Index on the _RequestorGuid_ column in the _BAR_Requests_ list, as this is one of the columns that gets filtered on in the _My Request List_ screen:
[// Get Users requests
ClearCollect(colUserRequests, SortByColumns(  Filter(BAR_Requests, RequestorGuid= varUser.id , RequestDate >=Today()) ,"RequestDate",Ascending));](url)

**Comment by bungleweed** [comment]
You could also consider Dataverse for Teams if you're seeding the PowerApp in Teams as a longer term option? Relational database vs SharePoint Lists could be a bit more scalable. Might help with the PowerBi reporting elements too.
