### ISSUE TITLE
Validating access using QR code 

### ISSUE THREAD

**Issue by KasWanders** [OfficeDev/microsoft-teams-apps-buildingaccess#41]
In a template demo file of Microsoft, the building access app seems to consist of a **QR code** which may be used by f.e. security officers to validate the access of visitors entering the building. Such validation would ensure that the number of visitors onsite is accurate. 

My team and I can't find any info on this QR code in this documentation. Is there a simple way to deploy this into the Building Access App or is there an indication when the script for this will be available? Thanks.

**Comment by v-smahaj** [comment]
For Building Access repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
