### ISSUE TITLE
Unable to Import BAR_CalendarReservations Power Automate

### ISSUE THREAD

**Issue by Scwardi** [OfficeDev/microsoft-teams-apps-buildingaccess#43]
![Capture (1)](https://user-images.githubusercontent.com/82787578/115169753-4126cb00-a102-11eb-9c2e-d40cff739a27.PNG)

Unable to complete installation as the BAR_CalendarReservations failed. error attached.

**Comment by v-smahaj** [comment]
Before importing the package, navigate to BARCalendarReservation.zip\Microsoft.Flow\flows\385cb5b1-c6c5-460a-bc7a-34b378bf7568\definition file and replace your SharePoint Site URL in place of existing one. Then, Save and import.
