### ISSUE TITLE
Missing parameter? 

### ISSUE THREAD

**Issue by tbuckley76** [OfficeDev/microsoft-teams-apps-buildingaccess#46]
The app is created but I can select a time slot in the application when booking a new request  I've double checked the deployment an there is no card "create event v4" in the BARCalendarReservation flow. Is this missing from the deployment guide images too?

**Comment by v-smahaj** [comment]
You can configure 'Time slot' in 'Settings' section of  'Building Admin' app.
You can find "Create event v4" card by navigating  to ''Condition'' > ''Apply to each'' > ''Condition 2'' card  in the BARCalendarReservation flow.
Let us know if issue still persists.
