### ISSUE TITLE
Calendar Appointments

### ISSUE THREAD

**Issue by DB-LEC** [OfficeDev/microsoft-teams-apps-buildingaccess#47]
Is there any way of turning off the Appointment the flows make in both the requestor and the approvers calendar? Just the Requestors calendar would be great but if a Manger has 20 -30 team members, their diary could look somewhat confused.

**Comment by v-smahaj** [comment]
We were not able to repro this issue at our end. The calendar is getting reserved for the requestor only.
Let us know if you are still facing the same issue.
