### ISSUE TITLE
Webcal.fi data source no longer available

### ISSUE THREAD

**Issue by modery** [OfficeDev/microsoft-teams-apps-buildingaccess#57]
The Power BI dashboard gets some data from webcal.fi (e.g. from a URL such as http://www.webcal.fi/cal.php?id=408&format=xml&start_year=2020&end_year=2025&tz=Europe%2FLondon). However, as of very recently (sometime during the past few days), the website is no longer available: "This site has been closed. Please switch to WebCal.Guru."

Thus, data refresh fails

**Comment by srb2115** [comment]
> The Power BI dashboard gets some data from webcal.fi (e.g. from a URL such as http://www.webcal.fi/cal.php?id=408&format=xml&start_year=2020&end_year=2025&tz=Europe%2FLondon). However, as of very recently (sometime during the past few days), the website is no longer available: "This site has been closed. Please switch to WebCal.Guru."
> 
> Thus, data refresh fails

Hey! Please let me know if you are able to see any work around for this. I am currently trying to at least make it so that we don't even need to run the check for Public Holidays.

**Comment by cristianoag** [comment]
Here is the solution https://tech-peanuts.com/2022/02/02/building-access-template-and-the-holidays-error/
