### ISSUE TITLE
Building Security - RequestCardComponent: hasPhoto & RequestorPhoto

### ISSUE THREAD

**Issue by MrHueb** [OfficeDev/microsoft-teams-apps-buildingaccess#58]
In the Building Security Power App, there are errors displayed in the RequestCardComponent input.
You can fix those by replacing the existing attributes with the following:

- hasPhoto: `!IsBlank(Office365Users.UserPhotoV2(varSelectedRequest.Requestor.Email))`

- RequestorPhoto: `If(!IsBlank(Office365Users.UserPhotoV2(varSelectedRequest.Requestor.Email)),Office365Users.UserPhotoV2(varSelectedRequest.Requestor.Email),ico_contacts)`

**Comment by cristianoag** [comment]
Thanks for the contribution @MrHueb.
