### ISSUE TITLE
Power BI - DataSource.Error in dates | webcal.fi closed

### ISSUE THREAD

**Issue by oscartexido** [OfficeDev/microsoft-teams-apps-buildingaccess#59]
I receive this error: 

DataSource.Error: Web.Contents failed to get contents from 'http://www.webcal.fi/cal.php?id=408&format=xml&start_year=2019&end_year=2035&tz=Europe%2FLondon' (404): Not Found
Details:
    DataSourceKind=Web
    DataSourcePath=http://www.webcal.fi/cal.php
    Url=http://www.webcal.fi/cal.php?id=408&format=xml&start_year=2019&end_year=2035&tz=Europe%2FLondon

![image](https://user-images.githubusercontent.com/94535224/142195785-64ddfdc8-ff64-4efd-83d1-cc4f6c25bde4.png)

When I try to access the link Url=http://www.webcal.fi/cal.phpid=408&format=xml&start_year=2019&end_year=2035&tz=Europe%2FLondon this appears:

![image](https://user-images.githubusercontent.com/94535224/142195971-c1548e96-69ea-4004-bf6f-64d9f86ea686.png)

How can I solve this? Thanks in advance!

**Comment by cristianoag** [comment]
You just need to remove all transformations after the PHTable creation. The reports will not consider public holidays tough. But that is actually not important as users can create reservations for any day. I'll make the change and publish the fixed version of the file later today

**Comment by cristianoag** [comment]
Here is the solution https://tech-peanuts.com/2022/02/02/building-access-template-and-the-holidays-error/

**Comment by cristianoag** [comment]
Closing this one as new versions of the PBIX files were provided without the dependency on webcal.fi
