### ISSUE TITLE
I can't edit my flow in power automate

### ISSUE THREAD

**Issue by makandmozart** [OfficeDev/microsoft-teams-apps-buildingaccess#6]
Hello

I am carefully deploying the manual https://github.com/OfficeDev/microsoft-teams-apps-buildingaccess/wiki/Deployment-guide

In the step where I am going to change the variables of the new flow, I cannot enter the edit section of the flow, I use windows 10 and explorer edge to avoid navigation problems

I attach the image that I get

What other information do you need? to discover the error

manual section
![00](https://user-images.githubusercontent.com/72475901/95269259-a8cc9700-07fe-11eb-9abd-725c18ec5b61.PNG)

List my flows
![01](https://user-images.githubusercontent.com/72475901/95269317-c7329280-07fe-11eb-9d09-331817098799.PNG)

details of my flow
![02](https://user-images.githubusercontent.com/72475901/95269350-d9143580-07fe-11eb-9da6-6912e008e701.PNG)

entering the edit command, it never finishes opening
![03](https://user-images.githubusercontent.com/72475901/95269419-f47f4080-07fe-11eb-9423-5c9a5e7bfe64.PNG)

When returning, comment that there is an error
![04](https://user-images.githubusercontent.com/72475901/95269468-0d87f180-07ff-11eb-9c59-52b419bd5433.PNG)

What do you think?

**Comment by yashrajmungale** [comment]
Tried to repro the issue but we were not able to. Can you try again and check if the issue still persists with you?

**Comment by stefanprobst78** [comment]
I had a similar issue. Actually, I was not able to save.
Turned out it is an issue if you use Flow on EMEA cloud... After several retries, it start working...
... but then the flow was not executable (Gateway error).

**Comment by yashrajmungale** [comment]
@stefanprobst78 Did you make any changes to make the flow working or did it start working by itself after refreshing? We can add a few pointers/guidance for folks trying it out on EMEA cloud based on your experience.

**Comment by yashrajmungale** [comment]
Marking this as closed as no further comment received. @stefanprobst78 Please reopen if the issue persists.
