### ISSUE TITLE
v1.0 of the app does not work if username does not match email address 

### ISSUE THREAD

**Issue by Nitecon01** [OfficeDev/microsoft-teams-apps-buildingaccess#60]
Users are able to use the app without any issues, book desks etc. These entries appear in the SharePoint list. However, when the user goes to "My Requests", there are no entries there.

They can then go back and book desks again on the same day.

We are running a very old version of the app, v1.0 from early 2020, would this issue be resolved in a newer release?

**Comment by cristianoag** [comment]
That is a known issue with the first release. You need to use v2 that is published here https://github.com/OfficeDev/microsoft-teams-apps-buildingaccess or you can change the filter that is used to present the requests directly on the Power App you're using. Just open for edition and change the filter on the Screen MyRequests, event OnVisible.
