### ISSUE TITLE
What's the point on BARCalendarReservation Flow?

### ISSUE THREAD

**Issue by dpreguezuelos** [OfficeDev/microsoft-teams-apps-buildingaccess#7]
I don't get why the flow convert the request date multiple times to the same time zone and adds a days to the request date. Then get the first calendar of the user thats deploy the flow, on my case the first calendar is birthdays calendar, that it's read-only and the flow fails.

**Comment by yashrajmungale** [comment]
@dpreguezuelos Can you please elaborate more? Not sure I understand your issue

**Comment by dpreguezuelos** [comment]
What is the function of the BARCalendarReservation  Flow? put an event on which calendar?

**Comment by yashrajmungale** [comment]
Yes, on building access request approval, it creates a Outlook and Teams calendar entry

**Comment by yashrajmungale** [comment]
Closing this as there is no further update. Kindly reopen this if you have additional questions regarding this
