### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by charlesosj** [OfficeDev/microsoft-teams-apps-buildingaccess#8]
Hi I'm not sure if it's me but, I think in an earlier version of the app is uploaded, I downloaded the git contents and the admin app has the old UI and no options for configuring the time slots

![image](https://user-images.githubusercontent.com/6671470/95494297-9df83a80-0995-11eb-9995-b25b3e000b6c.png)

**Comment by yashrajmungale** [comment]
@charlesosj Can you please check now?

**Comment by charlesosj** [comment]
@yashrajmungale  It seems to be the correct version now , thanks for the great work!!
